### ISSUE TITLE
Feature or bug?

### ISSUE THREAD

**Issue by Lohardt** [duythien/php-mongodb#3]
After creating a post using markdown, it is saved as html. When editing, the editor shows html and markdown wont work. Am i missing a configuration flag somewhere?

**Comment by duythien** [comment]
Currently It have not feature that, so you want to the feature you can use http://parsedown.org/

**Comment by Lohardt** [comment]
Ok, what i have done for now was to save both the markdown in $article['content'], and the html in $article['html']. I show the $article['content'] in the editor and $article['html'] in the views.

https://github.com/Lohardt/php-mongodb/commit/536e4e4ad86cacbd79e070ca53479f58fbafa98a

**Comment by duythien** [comment]
@Lohardt Can you created this pull request for me :)

**Comment by Lohardt** [comment]
Sure, Its done. :)

**Comment by duythien** [comment]
Thanks :)

**Comment by renjithvrs755** [comment]
Actually I'm not commenting about bug. I'm a new comer in web programing. I'm a student so I need to do the mini project work on this subject. I need to know how to successfully run this code on a windows system. I'm getting an error which shows  fatal error db.php file

**Comment by renjithvrs755** [comment]
Fatal error: Uncaught exception 'MongoConnectionException' with message 'Failed to connect to: 127.0.0.1:27017: SASL Authentication failed on database 'blog': Authentication failed.' in C:\xampp\htdocs\s\db.php:28 Stack trace: #0 C:\xampp\htdocs\s\db.php(28): MongoClient->__construct('mongodb://127.0...', Array) #1 C:\xampp\htdocs\s\db.php(19): Blog\DB\DB->connect(Array) #2 C:\xampp\htdocs\s\app.php(10): Blog\DB\DB->__construct(Array) #3 C:\xampp\htdocs\s\index.php(5): require('C:\xampp\htdocs...') #4 {main} thrown in C:\xampp\htdocs\s\db.php on line 28

I'm getting this error can you please tell me what is wrong..

**Comment by duythien** [comment]
@renjithvrs755 

You need change paramter config at https://github.com/duythien/php-mongodb/blob/master/config.php#L6 corresponding with your system
